# Generated by Django 3.0.5 on 2020-04-06 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, max_length=12, verbose_name='Код страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.PositiveIntegerField(verbose_name='Общее количество случаев заражения')),
                ('total_recovered', models.PositiveIntegerField(verbose_name='Общее количество выздоровевших')),
                ('total_unresolved', models.PositiveIntegerField(verbose_name='Общее количество не выявленных')),
                ('total_deaths', models.PositiveIntegerField(verbose_name='Общее количество смертей от вирус')),
                ('total_new_cases_today', models.PositiveIntegerField(verbose_name='Общее количество новых зараженных')),
                ('total_new_deaths_today', models.PositiveIntegerField(verbose_name='Общее количество новых смертей')),
                ('total_active_cases', models.PositiveIntegerField(verbose_name='Общее количество не выздоровевших')),
                ('total_serious_cases', models.PositiveIntegerField(verbose_name='Общее количество серьезно больных')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='country.Country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Статистика страны',
                'verbose_name_plural': 'Статистики стран',
            },
        ),
    ]
