# Generated by Django 2.1.7 on 2020-05-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20200516_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrystatistic',
            old_name='total_cases',
            new_name='confirmed',
        ),
        migrations.RenameField(
            model_name='countrystatistic',
            old_name='total_recovered',
            new_name='recovered',
        ),
        migrations.RemoveField(
            model_name='countrystatistic',
            name='total_active_cases',
        ),
        migrations.RemoveField(
            model_name='countrystatistic',
            name='total_deaths',
        ),
        migrations.RemoveField(
            model_name='countrystatistic',
            name='total_new_cases_today',
        ),
        migrations.RemoveField(
            model_name='countrystatistic',
            name='total_new_deaths_today',
        ),
        migrations.RemoveField(
            model_name='countrystatistic',
            name='total_serious_cases',
        ),
        migrations.RemoveField(
            model_name='countrystatistic',
            name='total_unresolved',
        ),
        migrations.AddField(
            model_name='countrystatistic',
            name='deaths',
            field=models.PositiveIntegerField(default=2, verbose_name='Общее количество смертей'),
            preserve_default=False,
        ),
    ]
