# Generated by Django 2.1.7 on 2020-05-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20200518_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrystatistic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='countrystatistic',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='countrystatistic',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
