# Generated by Django 2.1.7 on 2020-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20200521_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrystatistic',
            name='province',
            field=models.CharField(default='', max_length=255, verbose_name='Провинция'),
        ),
        migrations.AlterField(
            model_name='countrystatistic',
            name='confirmed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Общее количество случаев заражения'),
        ),
        migrations.AlterField(
            model_name='countrystatistic',
            name='deaths',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Общее количество смертей'),
        ),
        migrations.AlterField(
            model_name='countrystatistic',
            name='recovered',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Общее количество выздоровевших'),
        ),
    ]
