# Generated by Django 2.1.7 on 2020-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20200524_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrystatistic',
            name='province',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Провинция'),
        ),
    ]
